<?xml version="1.0"?>
<package format="2">
  <name>tiago_pick_place</name>
  <version>0.1.0</version>
  <description>TIAGo pick and place with frozen planning scene from MarkerArray.</description>

  <maintainer email="bangdong.zhang@tum.de">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>moveit_commander</depend>
  <depend>moveit_msgs</depend>
  <depend>shape_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>

  <export/>
</package>
